name: My First Workflow
on:
  push:
    branches: 
      - main
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Hello world"

      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: List files in the repository
        run: |
          echo "${{github.repository}} contains the followings files:"
          tree
