name: My first Workflow

on:
  push:
    branches:
      - main
  workflow-dispatch:
jobs:
  MyFirstJob:
    runs-on: ubtuntu-latest
    steps:
      - run: echo "Hello world."

      - name: Checkout
        uses: actions/checkout@3.5.2

      - name: List files in the repository
        run: |
          echo "${{github.repository}} contains the following files:"
          tree
